'use client'

import { useState, useRef, useCallback } from 'react'
import {
  ChevronRight, Upload, AlertCircle, FileText, ImageIcon,
  Loader2, CheckCircle, AlertTriangle, MessageCircle, Download,
} from 'lucide-react'
import Link from 'next/link'
import { useLanguage } from '@/lib/language-context'

interface ReportAnalysis {
  findings: string[]
  abnormalValues: string[]
  interpretation: string
  recommendations: string[]
  questionsToAsk: string[]
}

export default function ReportAnalyzerPage() {
  const { language, t } = useLanguage()
  const [file, setFile] = useState<File | null>(null)
  const [filePreview, setFilePreview] = useState<string>('')
  const [extractedText, setExtractedText] = useState('')
  const [analysis, setAnalysis] = useState<ReportAnalysis | null>(null)
  const [loading, setLoading] = useState(false)
  const [extracting, setExtracting] = useState(false)
  const [step, setStep] = useState<'upload' | 'review' | 'analysis'>('upload')
  const [dragOver, setDragOver] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const processFile = useCallback(async (selectedFile: File) => {
    setFile(selectedFile)
    setExtracting(true)
    try {
      if (selectedFile.type.startsWith('image/')) {
        const reader = new FileReader()
        reader.onload = async (ev) => {
          const dataUrl = ev.target?.result as string
          setFilePreview(dataUrl)
          // Use pdfjs/canvas OCR-like extraction via base64 to API
          setExtractedText(`[Image file: ${selectedFile.name}]\nPlease describe the content of this medical report or type the key values below for analysis.`)
          setExtracting(false)
        }
        reader.readAsDataURL(selectedFile)
      } else if (selectedFile.type === 'application/pdf') {
        setFilePreview(`PDF: ${selectedFile.name}`)
        // Read PDF as text using pdfjs
        const arrayBuffer = await selectedFile.arrayBuffer()
        try {
          const pdfjsLib = await import('pdfjs-dist')
          pdfjsLib.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.min.js`
          const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise
          let fullText = ''
          for (let i = 1; i <= Math.min(pdf.numPages, 10); i++) {
            const page = await pdf.getPage(i)
            const content = await page.getTextContent()
            fullText += content.items.map((item: any) => item.str).join(' ') + '\n'
          }
          setExtractedText(fullText.trim() || `PDF uploaded: ${selectedFile.name}. Text extraction completed.`)
        } catch {
          setExtractedText(`PDF: ${selectedFile.name}\n[Unable to extract text automatically. Please paste report content manually.]`)
        }
        setExtracting(false)
      } else {
        const text = await selectedFile.text()
        setExtractedText(text)
        setFilePreview(`Text file: ${selectedFile.name}`)
        setExtracting(false)
      }
    } catch {
      setExtractedText(`File: ${selectedFile.name}\nPlease paste the report content manually.`)
      setExtracting(false)
    }
  }, [])

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0]
    if (f) processFile(f)
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault(); setDragOver(false)
    const f = e.dataTransfer.files?.[0]
    if (f) processFile(f)
  }

  const handleAnalyze = async () => {
    if (!extractedText.trim()) { alert('Please provide report content.'); return }
    setLoading(true); setStep('analysis')
    try {
      const res = await fetch('/api/analyze-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          reportText: extractedText,
          reportImage: filePreview?.startsWith('data:') ? filePreview : undefined,
          language: language !== 'en' ? language : undefined,
        }),
      })
      if (!res.ok) throw new Error()
      setAnalysis(await res.json())
    } catch {
      alert('Error analyzing report. Please try again.'); setStep('review')
    } finally {
      setLoading(false)
    }
  }

  const downloadAnalysis = () => {
    if (!analysis) return
    const content = `MEDICAL REPORT ANALYSIS\n${'='.repeat(50)}\n\nFINDINGS:\n${analysis.findings.map((f, i) => `${i + 1}. ${f}`).join('\n')}\n\nABNORMAL VALUES:\n${analysis.abnormalValues.map((v, i) => `${i + 1}. ${v}`).join('\n')}\n\nINTERPRETATION:\n${analysis.interpretation}\n\nRECOMMENDATIONS:\n${analysis.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}\n\nQUESTIONS TO ASK YOUR DOCTOR:\n${analysis.questionsToAsk.map((q, i) => `${i + 1}. ${q}`).join('\n')}\n\nGenerated by MediRoute AI | ${new Date().toLocaleDateString()}`
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a'); a.href = url; a.download = 'report-analysis.txt'; a.click()
    URL.revokeObjectURL(url)
  }

  const addToChat = () => {
    const existing = sessionStorage.getItem('patientData')
    if (!existing) { alert('Please complete a health assessment first.'); return }
    const data = JSON.parse(existing)
    data.recentExams = `Report Analysis: ${analysis?.interpretation}`
    sessionStorage.setItem('patientData', JSON.stringify(data))
    // Add report context to chat
    const chatRaw = sessionStorage.getItem('chatMessages')
    const chat = chatRaw ? JSON.parse(chatRaw) : []
    chat.push({ id: Date.now().toString(), role: 'user', content: `I've uploaded a medical report. Here are the findings: ${analysis?.findings?.join(', ')}. Abnormal values: ${analysis?.abnormalValues?.join(', ')}. Please help me understand this.`, timestamp: new Date() })
    sessionStorage.setItem('chatMessages', JSON.stringify(chat))
    window.location.href = '/diagnosis/chat'
  }

  return (
    <main className="min-h-screen bg-gradient-ocean-light py-8">
      <div className="container-md mx-auto px-4">
        <div className="mb-6">
          <div className="flex items-center gap-2 text-sm mb-3">
            <Link href="/diagnosis" className="text-primary hover:underline">Diagnosis</Link>
            <ChevronRight className="w-3 h-3 text-muted-foreground" />
            <span className="text-muted-foreground">Report Analyzer</span>
          </div>
          <h1 className="text-3xl font-bold mb-1">{t('report.title')}</h1>
          <p className="text-muted-foreground">{t('report.subtitle')}</p>
        </div>

        <div className="p-4 bg-warning/5 border-l-4 border-l-warning rounded-lg mb-6 flex gap-3">
          <AlertCircle className="w-5 h-5 text-warning flex-shrink-0" />
          <p className="text-sm text-muted-foreground">AI analysis is informational only. Always consult your doctor for professional interpretation.</p>
        </div>

        {/* Progress */}
        <div className="flex items-center gap-2 mb-6">
          {['upload', 'review', 'analysis'].map((s, i) => (
            <div key={s} className="flex items-center gap-2">
              <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold transition-colors ${['upload', 'review', 'analysis'].indexOf(step) >= i ? 'bg-primary text-white' : 'bg-muted text-muted-foreground'}`}>{i + 1}</div>
              <span className="text-sm capitalize hidden sm:inline text-muted-foreground">{s}</span>
              {i < 2 && <ChevronRight className="w-4 h-4 text-muted-foreground" />}
            </div>
          ))}
        </div>

        {/* Upload Step */}
        {step === 'upload' && (
          <div className="card-lg space-y-5">
            <h2 className="text-xl font-bold">Upload Medical Report</h2>
            <div className="grid sm:grid-cols-4 gap-3">
              {[{icon: ImageIcon, label: 'Images', desc: 'JPG, PNG'}, {icon: FileText, label: 'PDF', desc: 'Lab reports'}, {icon: FileText, label: 'Text', desc: 'TXT files'}, {icon: FileText, label: 'Paste', desc: 'Copy text'}].map(f => (
                <div key={f.label} className="p-3 border border-border rounded-lg text-center">
                  <f.icon className="w-6 h-6 mx-auto mb-1 text-primary" />
                  <p className="text-sm font-semibold">{f.label}</p>
                  <p className="text-xs text-muted-foreground">{f.desc}</p>
                </div>
              ))}
            </div>

            {/* Drop zone */}
            <div
              onDragOver={e => { e.preventDefault(); setDragOver(true) }}
              onDragLeave={() => setDragOver(false)}
              onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}
              className={`border-2 border-dashed rounded-xl p-10 text-center cursor-pointer transition-all ${dragOver ? 'border-primary bg-primary/5' : 'border-border hover:border-primary/50 hover:bg-muted/30'}`}
            >
              <input ref={fileInputRef} type="file" accept=".jpg,.jpeg,.png,.pdf,.txt" onChange={handleFileSelect} className="hidden" />
              {extracting ? (
                <div className="flex flex-col items-center gap-2">
                  <Loader2 className="w-10 h-10 text-primary animate-spin" />
                  <p className="text-sm text-muted-foreground">Extracting text from file…</p>
                </div>
              ) : file ? (
                <div className="flex flex-col items-center gap-2">
                  <CheckCircle className="w-10 h-10 text-success" />
                  <p className="font-semibold">{file.name}</p>
                  <p className="text-sm text-muted-foreground">{(file.size / 1024).toFixed(1)} KB — Click to change</p>
                </div>
              ) : (
                <div className="flex flex-col items-center gap-2">
                  <Upload className="w-10 h-10 text-muted-foreground" />
                  <p className="font-semibold">Drag & drop or click to upload</p>
                  <p className="text-sm text-muted-foreground">PDF, JPG, PNG, TXT · Max 10MB</p>
                </div>
              )}
            </div>

            {/* Manual text input */}
            <div>
              <label className="block text-sm font-medium mb-1.5">Or paste report content</label>
              <textarea value={extractedText} onChange={e => setExtractedText(e.target.value)} className="textarea-field" placeholder="Paste your medical report, lab results, or prescription text here…" style={{ minHeight: 120 }} />
            </div>

            <div className="flex gap-3 pt-3 border-t border-border">
              <Link href="/diagnosis" className="btn btn-ghost">{t('common.back')}</Link>
              <button onClick={() => setStep('review')} disabled={!file && !extractedText.trim()} className="btn btn-primary ml-auto disabled:opacity-50">
                Review & Analyze
              </button>
            </div>
          </div>
        )}

        {/* Review Step */}
        {step === 'review' && (
          <div className="card-lg space-y-5">
            <h2 className="text-xl font-bold">Review Report</h2>
            {filePreview?.startsWith('data:image') && (
              <div className="rounded-lg overflow-hidden border border-border max-h-96 overflow-y-auto">
                <img src={filePreview} alt="Report" className="w-full" />
              </div>
            )}
            {extractedText && (
              <div>
                <p className="text-sm font-medium text-muted-foreground mb-2">Extracted Content:</p>
                <div className="p-4 bg-muted/30 rounded-lg max-h-64 overflow-y-auto whitespace-pre-wrap text-sm font-mono border border-border">{extractedText}</div>
                <p className="text-xs text-muted-foreground mt-1">You can edit this text before analysis</p>
                <textarea value={extractedText} onChange={e => setExtractedText(e.target.value)} className="textarea-field mt-2 text-sm" style={{ minHeight: 100 }} />
              </div>
            )}
            <div className="flex gap-3 pt-3 border-t border-border">
              <button onClick={() => setStep('upload')} className="btn btn-ghost">{t('common.back')}</button>
              <button onClick={handleAnalyze} disabled={loading} className="btn btn-primary ml-auto flex items-center gap-2">
                {loading && <Loader2 className="w-4 h-4 animate-spin" />}
                {loading ? 'Analyzing…' : 'Analyze Report'}
              </button>
            </div>
          </div>
        )}

        {/* Analysis Step */}
        {step === 'analysis' && loading && (
          <div className="card-lg text-center py-12">
            <Loader2 className="w-12 h-12 text-primary animate-spin mx-auto mb-4" />
            <p className="text-lg font-medium">Analyzing your report…</p>
            <p className="text-sm text-muted-foreground mt-1">AI is extracting insights from your medical data</p>
          </div>
        )}

        {step === 'analysis' && !loading && analysis && (
          <div className="space-y-5">
            {/* Findings */}
            <div className="card-lg p-5">
              <h2 className="font-bold mb-4 flex items-center gap-2"><CheckCircle className="w-4 h-4 text-success" /> Key Findings</h2>
              <ul className="space-y-2">
                {analysis.findings.map((f, i) => <li key={i} className="flex gap-2 text-sm"><span className="text-success font-bold">✓</span>{f}</li>)}
              </ul>
            </div>

            {/* Abnormal Values */}
            {analysis.abnormalValues.length > 0 && (
              <div className="card-lg p-5 border-l-4 border-l-warning">
                <h2 className="font-bold mb-4 flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-warning" /> Abnormal Values</h2>
                <ul className="space-y-2">
                  {analysis.abnormalValues.map((v, i) => <li key={i} className="flex gap-2 text-sm"><span className="text-warning font-bold">!</span>{v}</li>)}
                </ul>
              </div>
            )}

            {/* Interpretation */}
            <div className="card-lg p-5">
              <h2 className="font-bold mb-3">Interpretation</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">{analysis.interpretation}</p>
            </div>

            {/* Recommendations */}
            <div className="card-lg p-5">
              <h2 className="font-bold mb-4">Recommendations</h2>
              <ul className="space-y-2">
                {analysis.recommendations.map((r, i) => <li key={i} className="flex gap-2 text-sm"><span className="text-primary">→</span>{r}</li>)}
              </ul>
            </div>

            {/* Questions to ask */}
            {analysis.questionsToAsk?.length > 0 && (
              <div className="card-lg p-5 bg-primary/5 border border-primary/20">
                <h2 className="font-bold mb-4 text-primary">💬 Questions to Ask Your Doctor</h2>
                <ul className="space-y-2">
                  {analysis.questionsToAsk.map((q, i) => <li key={i} className="flex gap-2 text-sm"><span className="text-primary font-bold">{i + 1}.</span>{q}</li>)}
                </ul>
              </div>
            )}

            {/* Actions */}
            <div className="flex flex-wrap gap-3">
              <button onClick={() => { setStep('upload'); setFile(null); setExtractedText(''); setAnalysis(null) }} className="btn btn-ghost">Analyze Another</button>
              <button onClick={downloadAnalysis} className="btn btn-outline flex items-center gap-2"><Download className="w-4 h-4" /> Download</button>
              <button onClick={addToChat} className="btn btn-primary flex items-center gap-2"><MessageCircle className="w-4 h-4" /> Discuss in Chat</button>
              <Link href="/diagnosis/assessment" className="btn btn-secondary">Full Assessment</Link>
            </div>
          </div>
        )}
      </div>
    </main>
  )
}
