export const LANGUAGES = {
  en: { name: 'English', nativeName: 'English', code: 'en-US' },
  hi: { name: 'Hindi', nativeName: 'हिंदी', code: 'hi-IN' },
  ta: { name: 'Tamil', nativeName: 'தமிழ்', code: 'ta-IN' },
  ml: { name: 'Malayalam', nativeName: 'മലയാളം', code: 'ml-IN' },
  te: { name: 'Telugu', nativeName: 'తెలుగు', code: 'te-IN' },
  kn: { name: 'Kannada', nativeName: 'ಕನ್ನಡ', code: 'kn-IN' },
} as const

export type LanguageCode = keyof typeof LANGUAGES

// ─── MASTER TRANSLATION MAP ──────────────────────────────────────────────────
type TranslationMap = Record<string, string>
export const TRANSLATIONS: Record<LanguageCode, TranslationMap> = {
  en: {
    // Nav
    'nav.home':'Home','nav.services':'Services','nav.doctors':'Doctors',
    'nav.appointments':'Appointments','nav.about':'About','nav.contact':'Contact','nav.diagnosis':'AI Health',
    // Common
    'common.next':'Next','common.previous':'Previous','common.submit':'Submit','common.cancel':'Cancel',
    'common.back':'Back','common.download':'Download Report','common.print':'Print','common.loading':'Loading...',
    'common.error':'Error','common.success':'Success','common.save':'Save','common.close':'Close',
    'common.yes':'Yes','common.no':'No','common.male':'Male','common.female':'Female','common.other':'Other',
    'common.required':'This field is required','common.getStarted':'Get Started','common.learnMore':'Learn More',
    'common.bookAppointment':'Book Appointment','common.beginAssessment':'Begin Assessment',
    'common.aiHealthCheck':'AI Health Check',
    // Home
    'home.badge':'Welcome to MediRoute','home.hero.title':'Your Health is Our Priority',
    'home.hero.subtitle':'Experience world-class healthcare with AI-powered diagnosis, expert doctors, and instant medical insights.',
    'home.cta.title':'Feeling unwell? Get an instant AI health check',
    'home.cta.subtitle':'Chat with our AI doctor, analyze reports, find hospitals — available in 6 languages',
    'home.services.title':'Our Services','home.services.subtitle':'Comprehensive healthcare solutions designed to meet all your needs',
    'home.ready.title':'Ready to take care of your health?',
    'home.ready.subtitle':'Start with an AI-powered assessment or book a doctor appointment today.',
    'home.stat.patients':'Patients Served','home.stat.doctors':'Expert Doctors',
    'home.stat.treatments':'Successful Treatments','home.stat.years':'Years of Service',
    'home.service.doctors':'Expert Doctors','home.service.doctors.desc':'Highly qualified specialists with years of experience across all medical fields.',
    'home.service.appointments':'Easy Appointments','home.service.appointments.desc':'Book appointments online with flexible scheduling options available 24/7.',
    'home.service.emergency':'24/7 Emergency','home.service.emergency.desc':'Round-the-clock emergency care and ambulance services always available.',
    'home.service.care':'Advanced Care','home.service.care.desc':'State-of-the-art medical equipment and world-class treatment facilities.',
    'home.service.ai':'AI Health Assistant','home.service.ai.desc':'Instant AI-powered symptom analysis, report reading, and health guidance.',
    'home.service.hospitals':'Nearby Hospitals','home.service.hospitals.desc':'Find hospitals and clinics near you with real-time directions and ratings.',
    // Diagnosis Hub
    'diagnosis.powered':'Powered by Groq AI','diagnosis.title':'AI Health Assistant',
    'diagnosis.subtitle':'Get intelligent medical insights, chat with an AI doctor, find hospitals, and analyze your reports — all in one place.',
    'diagnosis.disclaimer':'Medical Disclaimer: This AI assistant is for informational purposes only and does not replace professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider. In emergencies, call 112 immediately.',
    'diagnosis.feature1.title':'AI Health Assessment','diagnosis.feature1.desc':'Comprehensive health intake with symptoms, lifestyle, blood group, and medical history — then talk directly to an AI doctor.',
    'diagnosis.feature2.title':'Nearby Hospitals','diagnosis.feature2.desc':'Find hospitals and medical facilities near your location with real-time directions and emergency services filter.',
    'diagnosis.feature3.title':'Report Analyzer','diagnosis.feature3.desc':'Upload blood reports, lab results, prescriptions, or discharge summaries for AI interpretation and simplified explanations.',
    'diagnosis.feature4.title':'Recovery Plan','diagnosis.feature4.desc':'Personalized daily recovery guide with diet, exercise, water intake, sleep, and medicine reminders with progress tracking.',
    'diagnosis.badge':'Start Here',
    'diagnosis.how.title':'How It Works',
    'diagnosis.step1.title':'Fill Health Form','diagnosis.step1.desc':'Enter symptoms, lifestyle, medical history, and personal details.',
    'diagnosis.step2.title':'AI Analysis','diagnosis.step2.desc':'AI analyzes your data and starts an intelligent doctor-like conversation.',
    'diagnosis.step3.title':'Get Insights','diagnosis.step3.desc':'Receive severity assessment, possible conditions, remedies, and a recovery plan.',
    'diagnosis.step4.title':'Find Care','diagnosis.step4.desc':'Locate nearby hospitals and download a full health report.',
    'diagnosis.ready.title':'Ready to Get Started?','diagnosis.ready.subtitle':'Complete your health assessment and chat with an AI doctor in minutes.',
    // Assessment
    'assessment.title':'AI Health Assessment','assessment.subtitle':'Provide your health details for AI analysis',
    'assessment.step1':'Personal Info','assessment.step2':'Symptoms','assessment.step3':'Medical History',
    'assessment.step4':'Lifestyle','assessment.step5':'Review',
    'assessment.fullName':'Full Name','assessment.age':'Age','assessment.gender':'Gender',
    'assessment.weight':'Weight (kg)','assessment.bloodGroup':'Blood Group','assessment.phone':'Phone Number',
    'assessment.allergies':'Allergies','assessment.symptoms':'Select Symptoms',
    'assessment.customSymptom':'Add Custom Symptom','assessment.duration':'Duration of Symptoms',
    'assessment.severity':'Severity','assessment.smoking':'Do you smoke?','assessment.alcohol':'Do you consume alcohol?',
    'assessment.pregnant':'Are you pregnant?','assessment.medications':'Current Medications',
    'assessment.medHistory':'Medical History','assessment.analyze':'Get AI Analysis',
    'assessment.analyzing':'AI is analyzing your data...','assessment.disclaimer':'This AI assessment is for informational purposes only and does NOT replace professional medical advice. In emergencies, call 112 immediately.',
    'assessment.afterSubmit':'After submission, our AI medical agent will analyze your data and begin an interactive consultation.',
    'assessment.namePlaceholder':'Enter your full name','assessment.agePlaceholder':'Enter your age',
    'assessment.phonePlaceholder':'Enter phone number','assessment.weightPlaceholder':'Enter weight in kg',
    'assessment.medPlaceholder':'List current medications','assessment.customSymptomPlaceholder':'Type a symptom and press Enter',
    'assessment.selectGender':'Select gender','assessment.selectBloodGroup':'Select blood group',
    'assessment.selectDuration':'Select duration','assessment.selectAtLeastOne':'Select at least one symptom',
    'assessment.validAge':'Enter a valid age (1-120)',
    // Chat
    'chat.title':'AI Consultation','chat.viewReport':'View Full Report','chat.clearChat':'Clear chat',
    'chat.disclaimer':'AI responses are informational only. Not a substitute for professional medical advice.',
    'chat.placeholder':'Describe your symptoms or ask a question... (Enter to send, Shift+Enter for new line)',
    'chat.typing':'MediBot is typing','chat.prompt1':'What are my possible conditions?',
    'chat.prompt2':'Suggest home remedies','chat.prompt3':'What medicines can I take?',
    'chat.prompt4':'Should I go to hospital?','chat.prompt5':'Give me a recovery plan',
    'chat.speakLast':'Speak last response',
    // Results
    'results.title':'Your Health Analysis','results.subtitle':'AI-powered insights based on your health information',
    'results.patientSummary':'Patient Summary','results.urgencyLevel':'Urgency Level',
    'results.conditions':'Possible Conditions','results.recommendations':'Recommendations',
    'results.homeRemedies':'Home Remedies','results.lifestyle':'Lifestyle Changes',
    'results.nextSteps':'Next Steps','results.medications':'Medications',
    'results.recovery':'Recovery Plan','results.diet':'Diet Plan','results.exercise':'Exercise Plan',
    'results.sleep':'Sleep','results.water':'Water Intake','results.warningSigns':'Warning Signs — Seek Immediate Care',
    'results.otcNote':'The following are general OTC guidance only. Always consult a pharmacist or doctor before taking any medication.',
    'results.continueChat':'Continue Chat','results.findHospitals':'Find Hospitals',
    'results.uploadReport':'Upload Report','results.recoveryPlan':'Recovery Plan',
    'results.tab.overview':'Overview','results.tab.recovery':'Recovery','results.tab.medications':'Medications',
    // Nearby Hospitals
    'hospitals.title':'Find Nearby Hospitals','hospitals.subtitle':'Locate medical facilities and get directions',
    'hospitals.all':'All','hospitals.emergency':'Emergency Only','hospitals.searchPlaceholder':'Search hospitals or specialties…',
    'hospitals.kmAway':'km away','hospitals.beds':'beds','hospitals.emergency24':'24/7 Emergency',
    'hospitals.directions':'Directions','hospitals.noResults':'No hospitals found. Try adjusting your search or filter.',
    'hospitals.enableLocation':'Enable location services for accurate distances. Showing sample hospital data.',
    // Report Analyzer
    'report.title':'Medical Report Analyzer','report.subtitle':'Upload blood reports, prescriptions, lab results, or discharge summaries for AI analysis',
    'report.disclaimer':'AI analysis is informational only. Always consult your doctor for professional interpretation.',
    'report.upload':'Upload Medical Report','report.dropzone':'Drag & drop or click to upload',
    'report.dropzoneDesc':'PDF, JPG, PNG, TXT · Max 10MB','report.pasteLabel':'Or paste report content',
    'report.pastePlaceholder':'Paste your medical report, lab results, or prescription text here…',
    'report.reviewTitle':'Review Report','report.extractedContent':'Extracted Content:',
    'report.editNote':'You can edit this text before analysis','report.analyzing':'Analyzing…',
    'report.analyzeBtn':'Analyze Report','report.findings':'Key Findings','report.abnormal':'Abnormal Values',
    'report.interpretation':'Interpretation','report.recommendations':'Recommendations',
    'report.questions':'Questions to Ask Your Doctor','report.analyzeAnother':'Analyze Another',
    'report.download':'Download','report.discussChat':'Discuss in Chat','report.fullAssessment':'Full Assessment',
    'report.extracting':'Extracting text from file…',
    // Recovery
    'recovery.title':'Personalized Recovery Plan','recovery.progress':'Today\'s Recovery Progress',
    'recovery.tasks':'daily tasks completed','recovery.water':'Water Intake','recovery.waterGoal':'Mark water goal as completed today',
    'recovery.sleep':'Sleep Recommendation','recovery.sleepGoal':'Good sleep last night',
    'recovery.diet':'Diet Plan','recovery.exercise':'Exercise Plan','recovery.medicines':'Medicine Reminders',
    'recovery.medicineWarning':'Always follow your doctor\'s prescription. Do not self-medicate.',
    'recovery.warning':'⚠️ Seek Immediate Medical Attention If:','recovery.emergency':'Emergency: Call 112 or go to the nearest hospital',
    'recovery.congrats':'Great job! 🎉','recovery.congratsDesc':'You\'ve completed all your recovery tasks for today. Keep it up!',
    'recovery.backToResults':'← Back to Results','recovery.chatDoctor':'Chat with AI Doctor',
    'recovery.takenToday':'Taken','recovery.noAssessment':'Please complete a health assessment first to get your personalized recovery plan.',
  },
  hi: {},
  ta: {},
  ml: {},
  te: {},
  kn: {},
}

// ─── HINDI ───────────────────────────────────────────────────────────────────
TRANSLATIONS.hi = {
  'nav.home':'होम','nav.services':'सेवाएं','nav.doctors':'डॉक्टर','nav.appointments':'अपॉइंटमेंट',
  'nav.about':'हमारे बारे में','nav.contact':'संपर्क','nav.diagnosis':'AI स्वास्थ्य',
  'common.next':'आगे','common.previous':'पीछे','common.submit':'जमा करें','common.cancel':'रद्द करें',
  'common.back':'वापस','common.download':'रिपोर्ट डाउनलोड करें','common.print':'प्रिंट करें','common.loading':'लोड हो रहा है...',
  'common.error':'त्रुटि','common.success':'सफलता','common.save':'सहेजें','common.close':'बंद करें',
  'common.yes':'हां','common.no':'नहीं','common.male':'पुरुष','common.female':'महिला','common.other':'अन्य',
  'common.required':'यह फ़ील्ड आवश्यक है','common.getStarted':'शुरू करें','common.learnMore':'और जानें',
  'common.bookAppointment':'अपॉइंटमेंट बुक करें','common.beginAssessment':'मूल्यांकन शुरू करें',
  'common.aiHealthCheck':'AI स्वास्थ्य जांच',
  'home.badge':'MediRoute में आपका स्वागत है','home.hero.title':'आपका स्वास्थ्य हमारी प्राथमिकता है',
  'home.hero.subtitle':'AI-संचालित निदान, विशेषज्ञ डॉक्टरों और त्वरित चिकित्सा अंतर्दृष्टि के साथ विश्व स्तरीय स्वास्थ्य सेवा का अनुभव करें।',
  'home.cta.title':'बीमार महसूस हो रहे हैं? तुरंत AI स्वास्थ्य जांच करें',
  'home.cta.subtitle':'हमारे AI डॉक्टर से चैट करें, रिपोर्ट विश्लेषण करें, अस्पताल खोजें — 6 भाषाओं में उपलब्ध',
  'home.services.title':'हमारी सेवाएं','home.services.subtitle':'आपकी सभी चिकित्सा आवश्यकताओं को पूरा करने के लिए व्यापक स्वास्थ्य सेवा समाधान',
  'home.ready.title':'अपने स्वास्थ्य की देखभाल करने के लिए तैयार हैं?',
  'home.ready.subtitle':'AI-संचालित मूल्यांकन के साथ शुरू करें या आज डॉक्टर की अपॉइंटमेंट बुक करें।',
  'home.stat.patients':'रोगियों की सेवा','home.stat.doctors':'विशेषज्ञ डॉक्टर',
  'home.stat.treatments':'सफल उपचार','home.stat.years':'सेवा के वर्ष',
  'home.service.doctors':'विशेषज्ञ डॉक्टर','home.service.doctors.desc':'सभी चिकित्सा क्षेत्रों में वर्षों के अनुभव वाले अत्यधिक योग्य विशेषज्ञ।',
  'home.service.appointments':'आसान अपॉइंटमेंट','home.service.appointments.desc':'24/7 उपलब्ध लचीले शेड्यूलिंग विकल्पों के साथ ऑनलाइन अपॉइंटमेंट बुक करें।',
  'home.service.emergency':'24/7 आपातकाल','home.service.emergency.desc':'चौबीसों घंटे आपातकालीन देखभाल और एम्बुलेंस सेवाएं हमेशा उपलब्ध।',
  'home.service.care':'उन्नत देखभाल','home.service.care.desc':'अत्याधुनिक चिकित्सा उपकरण और विश्व स्तरीय उपचार सुविधाएं।',
  'home.service.ai':'AI स्वास्थ्य सहायक','home.service.ai.desc':'तत्काल AI-संचालित लक्षण विश्लेषण, रिपोर्ट रीडिंग और स्वास्थ्य मार्गदर्शन।',
  'home.service.hospitals':'पास के अस्पताल','home.service.hospitals.desc':'रीयल-टाइम दिशाओं और रेटिंग के साथ आपके पास के अस्पताल और क्लीनिक खोजें।',
  'diagnosis.powered':'Groq AI द्वारा संचालित','diagnosis.title':'AI स्वास्थ्य सहायक',
  'diagnosis.subtitle':'बुद्धिमान चिकित्सा अंतर्दृष्टि प्राप्त करें, AI डॉक्टर से चैट करें, अस्पताल खोजें और अपनी रिपोर्ट का विश्लेषण करें।',
  'diagnosis.disclaimer':'चिकित्सा अस्वीकरण: यह AI सहायक केवल सूचनात्मक उद्देश्यों के लिए है और पेशेवर चिकित्सा सलाह का विकल्प नहीं है। आपात स्थिति में 112 पर कॉल करें।',
  'diagnosis.feature1.title':'AI स्वास्थ्य मूल्यांकन','diagnosis.feature1.desc':'लक्षण, जीवनशैली, रक्त समूह और चिकित्सा इतिहास के साथ व्यापक स्वास्थ्य सेवन।',
  'diagnosis.feature2.title':'पास के अस्पताल','diagnosis.feature2.desc':'रीयल-टाइम दिशाओं और आपातकालीन सेवाओं के साथ आपके स्थान के पास अस्पताल खोजें।',
  'diagnosis.feature3.title':'रिपोर्ट विश्लेषक','diagnosis.feature3.desc':'रक्त रिपोर्ट, लैब परिणाम, प्रिस्क्रिप्शन अपलोड करें AI व्याख्या के लिए।',
  'diagnosis.feature4.title':'रिकवरी योजना','diagnosis.feature4.desc':'आहार, व्यायाम, पानी का सेवन, नींद और दवा अनुस्मारक के साथ व्यक्तिगत दैनिक रिकवरी गाइड।',
  'diagnosis.badge':'यहां से शुरू करें','diagnosis.how.title':'यह कैसे काम करता है',
  'diagnosis.step1.title':'स्वास्थ्य फ़ॉर्म भरें','diagnosis.step1.desc':'लक्षण, जीवनशैली, चिकित्सा इतिहास और व्यक्तिगत विवरण दर्ज करें।',
  'diagnosis.step2.title':'AI विश्लेषण','diagnosis.step2.desc':'AI आपके डेटा का विश्लेषण करता है और एक बुद्धिमान डॉक्टर जैसी बातचीत शुरू करता है।',
  'diagnosis.step3.title':'अंतर्दृष्टि प्राप्त करें','diagnosis.step3.desc':'गंभीरता मूल्यांकन, संभावित स्थितियां, उपाय और रिकवरी योजना प्राप्त करें।',
  'diagnosis.step4.title':'देखभाल खोजें','diagnosis.step4.desc':'पास के अस्पताल खोजें और पूरी स्वास्थ्य रिपोर्ट डाउनलोड करें।',
  'diagnosis.ready.title':'शुरू करने के लिए तैयार हैं?','diagnosis.ready.subtitle':'मिनटों में स्वास्थ्य मूल्यांकन पूरा करें और AI डॉक्टर से चैट करें।',
  'assessment.title':'AI स्वास्थ्य मूल्यांकन','assessment.subtitle':'AI विश्लेषण के लिए अपना स्वास्थ्य विवरण दें',
  'assessment.step1':'व्यक्तिगत जानकारी','assessment.step2':'लक्षण','assessment.step3':'चिकित्सा इतिहास',
  'assessment.step4':'जीवनशैली','assessment.step5':'समीक्षा',
  'assessment.fullName':'पूरा नाम','assessment.age':'आयु','assessment.gender':'लिंग',
  'assessment.weight':'वजन (किग्रा)','assessment.bloodGroup':'रक्त समूह','assessment.phone':'फोन नंबर',
  'assessment.allergies':'एलर्जी','assessment.symptoms':'लक्षण चुनें','assessment.customSymptom':'कस्टम लक्षण जोड़ें',
  'assessment.duration':'लक्षणों की अवधि','assessment.severity':'गंभीरता',
  'assessment.smoking':'क्या आप धूम्रपान करते हैं?','assessment.alcohol':'क्या आप शराब पीते हैं?',
  'assessment.pregnant':'क्या आप गर्भवती हैं?','assessment.medications':'वर्तमान दवाएं',
  'assessment.medHistory':'चिकित्सा इतिहास','assessment.analyze':'AI विश्लेषण प्राप्त करें',
  'assessment.analyzing':'AI आपके डेटा का विश्लेषण कर रहा है...','assessment.disclaimer':'यह AI मूल्यांकन केवल सूचनात्मक उद्देश्यों के लिए है। आपात स्थिति में 112 पर कॉल करें।',
  'assessment.afterSubmit':'सबमिशन के बाद, हमारा AI मेडिकल एजेंट आपके डेटा का विश्लेषण करेगा और एक इंटरएक्टिव परामर्श शुरू करेगा।',
  'assessment.namePlaceholder':'अपना पूरा नाम दर्ज करें','assessment.agePlaceholder':'अपनी आयु दर्ज करें',
  'assessment.phonePlaceholder':'फोन नंबर दर्ज करें','assessment.weightPlaceholder':'किग्रा में वजन दर्ज करें',
  'assessment.medPlaceholder':'वर्तमान दवाओं की सूची','assessment.customSymptomPlaceholder':'लक्षण टाइप करें और Enter दबाएं',
  'assessment.selectGender':'लिंग चुनें','assessment.selectBloodGroup':'रक्त समूह चुनें',
  'assessment.selectDuration':'अवधि चुनें','assessment.selectAtLeastOne':'कम से कम एक लक्षण चुनें',
  'assessment.validAge':'एक वैध आयु दर्ज करें (1-120)',
  'chat.title':'AI परामर्श','chat.viewReport':'पूरी रिपोर्ट देखें','chat.clearChat':'चैट साफ़ करें',
  'chat.disclaimer':'AI प्रतिक्रियाएं केवल सूचनात्मक हैं। पेशेवर चिकित्सा सलाह का विकल्प नहीं।',
  'chat.placeholder':'अपने लक्षण बताएं या कोई प्रश्न पूछें...',
  'chat.typing':'MediBot टाइप कर रहा है','chat.prompt1':'मेरी संभावित स्थितियां क्या हैं?',
  'chat.prompt2':'घरेलू उपाय सुझाएं','chat.prompt3':'मैं कौन सी दवाएं ले सकता हूं?',
  'chat.prompt4':'क्या मुझे अस्पताल जाना चाहिए?','chat.prompt5':'रिकवरी योजना दें',
  'chat.speakLast':'अंतिम उत्तर बोलें',
  'results.title':'आपका स्वास्थ्य विश्लेषण','results.subtitle':'आपकी स्वास्थ्य जानकारी के आधार पर AI-संचालित अंतर्दृष्टि',
  'results.patientSummary':'रोगी सारांश','results.urgencyLevel':'तात्कालिकता स्तर',
  'results.conditions':'संभावित स्थितियां','results.recommendations':'सिफारिशें',
  'results.homeRemedies':'घरेलू उपाय','results.lifestyle':'जीवनशैली में बदलाव',
  'results.nextSteps':'अगले कदम','results.medications':'दवाएं',
  'results.recovery':'रिकवरी योजना','results.diet':'आहार योजना','results.exercise':'व्यायाम योजना',
  'results.sleep':'नींद','results.water':'पानी का सेवन','results.warningSigns':'चेतावनी संकेत — तुरंत चिकित्सा सहायता लें',
  'results.otcNote':'निम्नलिखित केवल सामान्य OTC मार्गदर्शन है। कोई भी दवा लेने से पहले डॉक्टर से परामर्श करें।',
  'results.continueChat':'चैट जारी रखें','results.findHospitals':'अस्पताल खोजें',
  'results.uploadReport':'रिपोर्ट अपलोड करें','results.recoveryPlan':'रिकवरी योजना',
  'results.tab.overview':'अवलोकन','results.tab.recovery':'रिकवरी','results.tab.medications':'दवाएं',
  'hospitals.title':'पास के अस्पताल खोजें','hospitals.subtitle':'चिकित्सा सुविधाएं खोजें और दिशाएं प्राप्त करें',
  'hospitals.all':'सभी','hospitals.emergency':'केवल आपातकाल','hospitals.searchPlaceholder':'अस्पताल या विशेषताएं खोजें...',
  'hospitals.kmAway':'किमी दूर','hospitals.beds':'बेड','hospitals.emergency24':'24/7 आपातकाल',
  'hospitals.directions':'दिशाएं','hospitals.noResults':'कोई अस्पताल नहीं मिला।',
  'hospitals.enableLocation':'सटीक दूरी के लिए स्थान सेवाएं सक्षम करें।',
  'report.title':'चिकित्सा रिपोर्ट विश्लेषक','report.subtitle':'AI विश्लेषण के लिए रक्त रिपोर्ट, प्रिस्क्रिप्शन, लैब परिणाम अपलोड करें',
  'report.disclaimer':'AI विश्लेषण केवल सूचनात्मक है। पेशेवर व्याख्या के लिए अपने डॉक्टर से परामर्श करें।',
  'report.upload':'चिकित्सा रिपोर्ट अपलोड करें','report.dropzone':'खींचें और छोड़ें या क्लिक करके अपलोड करें',
  'report.dropzoneDesc':'PDF, JPG, PNG, TXT · अधिकतम 10MB','report.pasteLabel':'या रिपोर्ट सामग्री पेस्ट करें',
  'report.pastePlaceholder':'अपनी चिकित्सा रिपोर्ट, लैब परिणाम यहां पेस्ट करें...','report.reviewTitle':'रिपोर्ट समीक्षा करें',
  'report.extractedContent':'निकाली गई सामग्री:','report.editNote':'विश्लेषण से पहले आप इस पाठ को संपादित कर सकते हैं',
  'report.analyzing':'विश्लेषण हो रहा है...','report.analyzeBtn':'रिपोर्ट विश्लेषण करें',
  'report.findings':'मुख्य निष्कर्ष','report.abnormal':'असामान्य मूल्य','report.interpretation':'व्याख्या',
  'report.recommendations':'सिफारिशें','report.questions':'अपने डॉक्टर से पूछने के लिए प्रश्न',
  'report.analyzeAnother':'दूसरी रिपोर्ट विश्लेषण करें','report.download':'डाउनलोड',
  'report.discussChat':'चैट में चर्चा करें','report.fullAssessment':'पूर्ण मूल्यांकन',
  'report.extracting':'फ़ाइल से टेक्स्ट निकाला जा रहा है...',
  'recovery.title':'व्यक्तिगत रिकवरी योजना','recovery.progress':'आज की रिकवरी प्रगति',
  'recovery.tasks':'दैनिक कार्य पूर्ण','recovery.water':'पानी का सेवन','recovery.waterGoal':'आज का पानी लक्ष्य पूरा हुआ',
  'recovery.sleep':'नींद की सिफारिश','recovery.sleepGoal':'कल रात अच्छी नींद आई',
  'recovery.diet':'आहार योजना','recovery.exercise':'व्यायाम योजना','recovery.medicines':'दवा अनुस्मारक',
  'recovery.medicineWarning':'हमेशा अपने डॉक्टर के पर्चे का पालन करें। बिना मार्गदर्शन के दवा न लें।',
  'recovery.warning':'⚠️ तुरंत चिकित्सा सहायता लें यदि:','recovery.emergency':'आपातकाल: 112 पर कॉल करें',
  'recovery.congrats':'शाबाश! 🎉','recovery.congratsDesc':'आपने आज के सभी रिकवरी कार्य पूरे कर लिए हैं!',
  'recovery.backToResults':'← परिणाम पर वापस','recovery.chatDoctor':'AI डॉक्टर से चैट करें',
  'recovery.takenToday':'लिया गया','recovery.noAssessment':'कृपया पहले एक स्वास्थ्य मूल्यांकन पूरा करें।',
}

// ─── TAMIL ────────────────────────────────────────────────────────────────────
TRANSLATIONS.ta = {
  'nav.home':'முகப்பு','nav.services':'சேவைகள்','nav.doctors':'மருத்துவர்கள்','nav.appointments':'சந்திப்புகள்',
  'nav.about':'எங்களை பற்றி','nav.contact':'தொடர்பு','nav.diagnosis':'AI சுகாதாரம்',
  'common.next':'அடுத்து','common.previous':'முந்தைய','common.submit':'சமர்ப்பிக்கவும்','common.cancel':'ரத்து',
  'common.back':'பின்செல்','common.download':'அறிக்கை பதிவிறக்கம்','common.print':'அச்சிடு','common.loading':'ஏற்றுகிறது...',
  'common.error':'பிழை','common.success':'வெற்றி','common.save':'சேமி','common.close':'மூடு',
  'common.yes':'ஆம்','common.no':'இல்லை','common.male':'ஆண்','common.female':'பெண்','common.other':'மற்றவை',
  'common.required':'இந்த புலம் தேவை','common.getStarted':'தொடங்குங்கள்','common.learnMore':'மேலும் அறியுங்கள்',
  'common.bookAppointment':'சந்திப்பு பதிவு','common.beginAssessment':'மதிப்பீட்டை தொடங்கு',
  'common.aiHealthCheck':'AI சுகாதார சோதனை',
  'home.badge':'MediRoute-க்கு வரவேற்கிறோம்','home.hero.title':'உங்கள் ஆரோக்கியம் எங்கள் முன்னுரிமை',
  'home.hero.subtitle':'AI-சக்தி கொண்ட நோயறிதல், நிபுணர் மருத்துவர்கள் மற்றும் உடனடி மருத்துவ நுண்ணறிவுடன் உலகத்தரம் வாய்ந்த சுகாதாரத்தை அனுபவியுங்கள்.',
  'home.cta.title':'உடல் நலமில்லையா? உடனடி AI சுகாதார சோதனை செய்யுங்கள்',
  'home.cta.subtitle':'எங்கள் AI மருத்துவரிடம் கதைக்கவும், அறிக்கைகளை பகுப்பாய்வு செய்யவும் — 6 மொழிகளில் கிடைக்கும்',
  'home.services.title':'எங்கள் சேவைகள்','home.services.subtitle':'உங்கள் அனைத்து மருத்துவ தேவைகளையும் பூர்த்தி செய்ய விரிவான சுகாதார தீர்வுகள்',
  'home.ready.title':'உங்கள் ஆரோக்கியத்தை கவனித்துக்கொள்ள தயாரா?',
  'home.ready.subtitle':'AI மதிப்பீட்டுடன் தொடங்குங்கள் அல்லது இன்றே மருத்துவர் சந்திப்பை பதிவு செய்யுங்கள்.',
  'home.stat.patients':'நோயாளிகள் சேவை','home.stat.doctors':'நிபுணர் மருத்துவர்கள்',
  'home.stat.treatments':'வெற்றிகரமான சிகிச்சைகள்','home.stat.years':'சேவை ஆண்டுகள்',
  'home.service.doctors':'நிபுணர் மருத்துவர்கள்','home.service.doctors.desc':'அனைத்து மருத்துவ துறைகளிலும் ஆண்டுகள் அனுபவம் வாய்ந்த தகுதி வாய்ந்த நிபுணர்கள்.',
  'home.service.appointments':'எளிய சந்திப்புகள்','home.service.appointments.desc':'24/7 கிடைக்கும் நெகிழ்வான திட்டமிடல் விருப்பங்களுடன் ஆன்லைனில் சந்திப்பு பதிவு செய்யுங்கள்.',
  'home.service.emergency':'24/7 அவசரநிலை','home.service.emergency.desc':'சுற்று-ஒரு-கடிகாரம் அவசர கவனிப்பு மற்றும் ஆம்புலன்ஸ் சேவைகள் எப்போதும் கிடைக்கும்.',
  'home.service.care':'மேம்பட்ட கவனிப்பு','home.service.care.desc':'நவீன மருத்துவ உபகரணங்கள் மற்றும் உலகத்தரம் வாய்ந்த சிகிச்சை வசதிகள்.',
  'home.service.ai':'AI சுகாதார உதவியாளர்','home.service.ai.desc':'உடனடி AI-சக்தி கொண்ட அறிகுறி பகுப்பாய்வு, அறிக்கை வாசிப்பு மற்றும் சுகாதார வழிகாட்டுதல்.',
  'home.service.hospitals':'அருகிலுள்ள மருத்துவமனைகள்','home.service.hospitals.desc':'நிகழ்நேர திசைகள் மற்றும் மதிப்பீடுகளுடன் உங்களுக்கு அருகில் உள்ள மருத்துவமனைகளை கண்டுபிடிக்கவும்.',
  'diagnosis.powered':'Groq AI ஆல் இயக்கப்படுகிறது','diagnosis.title':'AI சுகாதார உதவியாளர்',
  'diagnosis.subtitle':'புத்திசாலி மருத்துவ நுண்ணறிவு பெறுங்கள், AI மருத்துவரிடம் கதைக்கவும், மருத்துவமனைகளை கண்டுபிடிக்கவும்.',
  'diagnosis.disclaimer':'மருத்துவ அறிவிப்பு: இந்த AI உதவியாளர் தகவல் நோக்கங்களுக்கு மட்டுமே. அவசரநிலையில் 112 அழைக்கவும்.',
  'diagnosis.feature1.title':'AI சுகாதார மதிப்பீடு','diagnosis.feature1.desc':'அறிகுறிகள், வாழ்க்கை முறை, இரத்த வகை மற்றும் மருத்துவ வரலாறுடன் AI மருத்துவரிடம் நேரடியாக பேசுங்கள்.',
  'diagnosis.feature2.title':'அருகிலுள்ள மருத்துவமனைகள்','diagnosis.feature2.desc':'நிகழ்நேர திசைகள் மற்றும் அவசர சேவைகளுடன் உங்கள் இடத்திற்கு அருகில் உள்ள மருத்துவமனைகளை கண்டுபிடிக்கவும்.',
  'diagnosis.feature3.title':'அறிக்கை பகுப்பாய்வியல்','diagnosis.feature3.desc':'இரத்த அறிக்கைகள், ஆய்வக முடிவுகள், மருந்துச்சீட்டு அனுப்புங்கள் AI விளக்கத்திற்காக.',
  'diagnosis.feature4.title':'மீட்பு திட்டம்','diagnosis.feature4.desc':'உணவு, உடற்பயிற்சி, தண்ணீர் உட்கொள்ளல், தூக்கம் மற்றும் மருந்து நினைவூட்டல்களுடன் தனிப்பட்ட மீட்பு வழிகாட்டி.',
  'diagnosis.badge':'இங்கே தொடங்குங்கள்','diagnosis.how.title':'இது எப்படி செயல்படுகிறது',
  'diagnosis.step1.title':'சுகாதார படிவத்தை நிரப்புங்கள்','diagnosis.step1.desc':'அறிகுறிகள், வாழ்க்கை முறை, மருத்துவ வரலாறு மற்றும் தனிப்பட்ட விவரங்களை உள்ளிடுங்கள்.',
  'diagnosis.step2.title':'AI பகுப்பாய்வு','diagnosis.step2.desc':'AI உங்கள் தரவை பகுப்பாய்ந்து ஒரு புத்திசாலி மருத்துவர் போன்ற உரையாடலை தொடங்குகிறது.',
  'diagnosis.step3.title':'நுண்ணறிவு பெறுங்கள்','diagnosis.step3.desc':'தீவிரம் மதிப்பீடு, சாத்தியமான நிலைகள், தீர்வுகள் மற்றும் மீட்பு திட்டம் பெறுங்கள்.',
  'diagnosis.step4.title':'கவனிப்பு கண்டுபிடிக்கவும்','diagnosis.step4.desc':'அருகிலுள்ள மருத்துவமனைகளை கண்டுபிடித்து முழு சுகாதார அறிக்கையை பதிவிறக்கம் செய்யுங்கள்.',
  'diagnosis.ready.title':'தொடங்க தயாரா?','diagnosis.ready.subtitle':'நிமிடங்களில் சுகாதார மதிப்பீட்டை முடித்து AI மருத்துவரிடம் கதைக்கவும்.',
  'assessment.title':'AI சுகாதார மதிப்பீடு','assessment.subtitle':'AI பகுப்பாய்வுக்கு உங்கள் சுகாதார விவரங்களை வழங்கவும்',
  'assessment.step1':'தனிப்பட்ட தகவல்','assessment.step2':'அறிகுறிகள்','assessment.step3':'மருத்துவ வரலாறு',
  'assessment.step4':'வாழ்க்கை முறை','assessment.step5':'மதிப்பாய்வு',
  'assessment.fullName':'முழு பெயர்','assessment.age':'வயது','assessment.gender':'பாலினம்',
  'assessment.weight':'எடை (கிகி)','assessment.bloodGroup':'இரத்த வகை','assessment.phone':'தொலைபேசி எண்',
  'assessment.allergies':'ஒவ்வாமை','assessment.symptoms':'அறிகுறிகளை தேர்ந்தெடுக்கவும்',
  'assessment.customSymptom':'தனிப்பயன் அறிகுறி சேர்க்கவும்','assessment.duration':'அறிகுறிகளின் கால அளவு',
  'assessment.severity':'தீவிரம்','assessment.smoking':'நீங்கள் புகைபிடிக்கிறீர்களா?',
  'assessment.alcohol':'நீங்கள் மது அருந்துகிறீர்களா?','assessment.pregnant':'நீங்கள் கர்ப்பமாக இருக்கிறீர்களா?',
  'assessment.medications':'தற்போதைய மருந்துகள்','assessment.medHistory':'மருத்துவ வரலாறு',
  'assessment.analyze':'AI பகுப்பாய்வு பெறவும்','assessment.analyzing':'AI உங்கள் தரவை பகுப்பாய்கிறது...',
  'assessment.disclaimer':'இந்த AI மதிப்பீடு தகவல் நோக்கங்களுக்கு மட்டுமே. அவசரநிலையில் 112 அழைக்கவும்.',
  'assessment.afterSubmit':'சமர்ப்பித்த பிறகு, எங்கள் AI மருத்துவர் உங்கள் தரவை பகுப்பாய்ந்து ஒரு ஊடாடும் ஆலோசனையை தொடங்குவார்.',
  'assessment.namePlaceholder':'உங்கள் முழு பெயரை உள்ளிடவும்','assessment.agePlaceholder':'உங்கள் வயதை உள்ளிடவும்',
  'assessment.phonePlaceholder':'தொலைபேசி எண்ணை உள்ளிடவும்','assessment.weightPlaceholder':'கிகியில் எடையை உள்ளிடவும்',
  'assessment.medPlaceholder':'தற்போதைய மருந்துகளின் பட்டியல்','assessment.customSymptomPlaceholder':'அறிகுறியை தட்டச்சு செய்து Enter அழுத்தவும்',
  'assessment.selectGender':'பாலினம் தேர்ந்தெடுக்கவும்','assessment.selectBloodGroup':'இரத்த வகை தேர்ந்தெடுக்கவும்',
  'assessment.selectDuration':'காலம் தேர்ந்தெடுக்கவும்','assessment.selectAtLeastOne':'குறைந்தது ஒரு அறிகுறியை தேர்ந்தெடுக்கவும்',
  'assessment.validAge':'சரியான வயதை உள்ளிடவும் (1-120)',
  'chat.title':'AI ஆலோசனை','chat.viewReport':'முழு அறிக்கை பார்க்கவும்','chat.clearChat':'அரட்டையை அழிக்கவும்',
  'chat.disclaimer':'AI பதில்கள் தகவல் மட்டுமே. தொழில்முறை மருத்துவ ஆலோசனைக்கு மாற்றாகாது.',
  'chat.placeholder':'உங்கள் அறிகுறிகளை விவரிக்கவும் அல்லது கேள்வி கேட்கவும்...',
  'chat.typing':'MediBot தட்டச்சு செய்கிறது','chat.prompt1':'என் சாத்தியமான நிலைகள் என்ன?',
  'chat.prompt2':'வீட்டு வைத்தியம் பரிந்துரைக்கவும்','chat.prompt3':'நான் என்ன மருந்துகள் எடுக்கலாம்?',
  'chat.prompt4':'நான் மருத்துவமனை போக வேண்டுமா?','chat.prompt5':'மீட்பு திட்டம் தரவும்',
  'chat.speakLast':'கடைசி பதிலை படிக்கவும்',
  'results.title':'உங்கள் சுகாதார பகுப்பாய்வு','results.subtitle':'உங்கள் சுகாதார தகவலின் அடிப்படையில் AI நுண்ணறிவு',
  'results.patientSummary':'நோயாளர் சுருக்கம்','results.urgencyLevel':'அவசரநிலை நிலை',
  'results.conditions':'சாத்தியமான நிலைகள்','results.recommendations':'பரிந்துரைகள்',
  'results.homeRemedies':'வீட்டு வைத்தியம்','results.lifestyle':'வாழ்க்கை முறை மாற்றங்கள்',
  'results.nextSteps':'அடுத்த படிகள்','results.medications':'மருந்துகள்',
  'results.recovery':'மீட்பு திட்டம்','results.diet':'உணவு திட்டம்','results.exercise':'உடற்பயிற்சி திட்டம்',
  'results.sleep':'தூக்கம்','results.water':'தண்ணீர் உட்கொள்ளல்','results.warningSigns':'எச்சரிக்கை அறிகுறிகள் — உடனடி மருத்துவ கவனிப்பு தேடுங்கள்',
  'results.otcNote':'பின்வருபவை பொதுவான OTC வழிகாட்டுதல் மட்டுமே. எந்த மருந்தும் எடுப்பதற்கு முன் மருத்துவரை அணுகவும்.',
  'results.continueChat':'அரட்டையை தொடரவும்','results.findHospitals':'மருத்துவமனைகளை கண்டுபிடிக்கவும்',
  'results.uploadReport':'அறிக்கை பதிவேற்றம்','results.recoveryPlan':'மீட்பு திட்டம்',
  'results.tab.overview':'மேலோட்டம்','results.tab.recovery':'மீட்பு','results.tab.medications':'மருந்துகள்',
  'hospitals.title':'அருகிலுள்ள மருத்துவமனைகளை கண்டுபிடிக்கவும்','hospitals.subtitle':'மருத்துவ வசதிகளை கண்டுபிடித்து திசைகள் பெறுங்கள்',
  'hospitals.all':'அனைத்தும்','hospitals.emergency':'அவசரநிலை மட்டும்','hospitals.searchPlaceholder':'மருத்துவமனை அல்லது சிறப்புகளை தேடுங்கள்...',
  'hospitals.kmAway':'கிமீ தூரம்','hospitals.beds':'படுக்கைகள்','hospitals.emergency24':'24/7 அவசரநிலை',
  'hospitals.directions':'திசைகள்','hospitals.noResults':'மருத்துவமனை இல்லை. வடிப்பானை சரிசெய்யவும்.',
  'hospitals.enableLocation':'சரியான தூரத்திற்கு இட சேவைகளை இயக்கவும்.',
  'report.title':'மருத்துவ அறிக்கை பகுப்பாய்வியல்','report.subtitle':'AI பகுப்பாய்வுக்கு இரத்த அறிக்கைகள், மருந்துச்சீட்டு, ஆய்வக முடிவுகள் பதிவேற்றவும்',
  'report.disclaimer':'AI பகுப்பாய்வு தகவல் மட்டுமே. தொழில்முறை விளக்கத்திற்கு உங்கள் மருத்துவரை அணுகவும்.',
  'report.upload':'மருத்துவ அறிக்கையை பதிவேற்றவும்','report.dropzone':'இழுத்து விடுங்கள் அல்லது கிளிக் செய்து பதிவேற்றவும்',
  'report.dropzoneDesc':'PDF, JPG, PNG, TXT · அதிகபட்சம் 10MB','report.pasteLabel':'அல்லது அறிக்கை உள்ளடக்கத்தை ஒட்டவும்',
  'report.pastePlaceholder':'உங்கள் மருத்துவ அறிக்கையை இங்கே ஒட்டவும்...','report.reviewTitle':'அறிக்கையை மதிப்பாய்வு செய்யவும்',
  'report.extractedContent':'பிரித்தெடுக்கப்பட்ட உள்ளடக்கம்:','report.editNote':'பகுப்பாய்வுக்கு முன் இந்த உரையை திருத்தலாம்',
  'report.analyzing':'பகுப்பாய்வு செய்கிறது...','report.analyzeBtn':'அறிக்கையை பகுப்பாய்வு செய்யவும்',
  'report.findings':'முக்கிய கண்டுபிடிப்புகள்','report.abnormal':'அசாதாரண மதிப்புகள்',
  'report.interpretation':'விளக்கம்','report.recommendations':'பரிந்துரைகள்',
  'report.questions':'உங்கள் மருத்துவரிடம் கேட்க வேண்டிய கேள்விகள்',
  'report.analyzeAnother':'வேறு அறிக்கையை பகுப்பாய்வு செய்யவும்','report.download':'பதிவிறக்கம்',
  'report.discussChat':'அரட்டையில் விவாதிக்கவும்','report.fullAssessment':'முழு மதிப்பீடு',
  'report.extracting':'கோப்பிலிருந்து உரையை பிரித்தெடுக்கிறது...',
  'recovery.title':'தனிப்பட்ட மீட்பு திட்டம்','recovery.progress':'இன்றைய மீட்பு முன்னேற்றம்',
  'recovery.tasks':'தினசரி பணிகள் முடிந்தன','recovery.water':'தண்ணீர் உட்கொள்ளல்','recovery.waterGoal':'இன்றைய தண்ணீர் இலக்கு முடிந்தது',
  'recovery.sleep':'தூக்க பரிந்துரை','recovery.sleepGoal':'நேற்று இரவு நல்ல தூக்கம் வந்தது',
  'recovery.diet':'உணவு திட்டம்','recovery.exercise':'உடற்பயிற்சி திட்டம்','recovery.medicines':'மருந்து நினைவூட்டல்கள்',
  'recovery.medicineWarning':'எப்போதும் உங்கள் மருத்துவரின் மருந்துச்சீட்டை பின்பற்றவும்.',
  'recovery.warning':'⚠️ உடனடி மருத்துவ கவனிப்பு தேடுங்கள் என்றால்:','recovery.emergency':'அவசரநிலை: 112 அழைக்கவும்',
  'recovery.congrats':'சாபாஷ்! 🎉','recovery.congratsDesc':'இன்றைய அனைத்து மீட்பு பணிகளையும் முடித்துவிட்டீர்கள்!',
  'recovery.backToResults':'← முடிவுகளுக்கு திரும்பு','recovery.chatDoctor':'AI மருத்துவரிடம் கதைக்கவும்',
  'recovery.takenToday':'எடுக்கப்பட்டது','recovery.noAssessment':'தனிப்பட்ட மீட்பு திட்டம் பெற முதலில் ஒரு சுகாதார மதிப்பீட்டை முடிக்கவும்.',
}

// ─── MALAYALAM, TELUGU, KANNADA — copy English as fallback (displayed via t() fallback) ─
// Full translations stored; t() falls back to English automatically if key missing
TRANSLATIONS.ml = { ...TRANSLATIONS.en,
  'nav.home':'ഹോം','nav.services':'സേവനങ്ങൾ','nav.doctors':'ഡോക്ടർമാർ','nav.appointments':'അപ്പോയ്‌ന്റ്‌മെന്റുകൾ','nav.about':'ഞങ്ങളെ കുറിച്ച്','nav.contact':'ബന്ധപ്പെടുക','nav.diagnosis':'AI ആരോഗ്യം',
  'common.next':'അടുത്തത്','common.previous':'മുൻ','common.submit':'സമർപ്പിക്കുക','common.cancel':'റദ്ദാക്കുക','common.back':'തിരിച്ച്','common.download':'റിപ്പോർട്ട് ഡൗൺലോഡ്','common.print':'പ്രിന്റ്','common.loading':'ലോഡ് ചെയ്യുന്നു...','common.yes':'അതെ','common.no':'ഇല്ല','common.male':'പുരുഷൻ','common.female':'സ്ത്രീ','common.other':'മറ്റുള്ളവ','common.required':'ഈ ഫീൽഡ് ആവശ്യമാണ്','common.getStarted':'ആരംഭിക്കുക','common.learnMore':'കൂടുതൽ അറിയുക','common.bookAppointment':'അപ്പോയ്‌ന്റ്‌മെന്റ് ബുക്ക് ചെയ്യുക','common.beginAssessment':'മൂല്യനിർണ്ണയം ആരംഭിക്കുക','common.aiHealthCheck':'AI ആരോഗ്യ പരിശോധന',
  'home.hero.title':'നിങ്ങളുടെ ആരോഗ്യം ഞങ്ങളുടെ മുൻഗണനയാണ്','home.hero.subtitle':'AI-ശക്തിയുള്ള ഡയഗ്നോസിസ്, വിദഗ്ധ ഡോക്ടർമാർ, ഉടനടി വൈദ്യ ഉൾക്കാഴ്ചകൾ എന്നിവയോടെ ലോകോത്തര ആരോഗ്യ സേവനം അനുഭവിക്കൂ.',
  'diagnosis.title':'AI ആരോഗ്യ സഹായി','assessment.title':'AI ആരോഗ്യ മൂല്യനിർണ്ണയം','assessment.step1':'വ്യക്തിഗത വിവരം','assessment.step2':'ലക്ഷണങ്ങൾ','assessment.step3':'വൈദ്യ ചരിത്രം','assessment.step4':'ജീവിതശൈലി','assessment.step5':'അവലോകനം',
  'assessment.fullName':'പൂർണ്ണ നാമം','assessment.age':'പ്രായം','assessment.gender':'ലിംഗം','assessment.weight':'ഭാരം (കിഗ്രാ)','assessment.bloodGroup':'രക്ത ഗ്രൂപ്പ്','assessment.phone':'ഫോൺ നമ്പർ','assessment.allergies':'അലർജികൾ','assessment.symptoms':'ലക്ഷണങ്ങൾ തിരഞ്ഞെടുക്കുക','assessment.analyze':'AI വിശകലനം നേടുക','assessment.analyzing':'AI നിങ്ങളുടെ ഡേറ്റ വിശകലനം ചെയ്യുന്നു...',
  'chat.title':'AI കൂടിയാലോചന','results.title':'നിങ്ങളുടെ ആരോഗ്യ വിശകലനം',
  'hospitals.title':'അടുത്തുള്ള ആശുപത്രികൾ കണ്ടെത്തുക','report.title':'മെഡിക്കൽ റിപ്പോർട്ട് അനലൈസർ','recovery.title':'വ്യക്തിഗത വീണ്ടെടുക്കൽ പദ്ധതി',
}

TRANSLATIONS.te = { ...TRANSLATIONS.en,
  'nav.home':'హోమ్','nav.services':'సేవలు','nav.doctors':'డాక్టర్లు','nav.appointments':'అపాయింట్‌మెంట్లు','nav.about':'మా గురించి','nav.contact':'సంప్రదించండి','nav.diagnosis':'AI ఆరోగ్యం',
  'common.next':'తదుపరి','common.previous':'వెనుక','common.submit':'సమర్పించండి','common.cancel':'రద్దు','common.back':'వెనక్కు','common.download':'నివేదిక డౌన్‌లోడ్','common.print':'ముద్రించు','common.loading':'లోడ్ అవుతోంది...','common.yes':'అవును','common.no':'కాదు','common.male':'పురుషుడు','common.female':'స్త్రీ','common.other':'ఇతర','common.required':'ఈ ఫీల్డ్ అవసరం','common.getStarted':'ప్రారంభించండి','common.learnMore':'మరింత తెలుసుకోండి','common.bookAppointment':'అపాయింట్‌మెంట్ బుక్ చేయండి','common.beginAssessment':'మూల్యాంకనం ప్రారంభించండి','common.aiHealthCheck':'AI ఆరోగ్య తనిఖీ',
  'home.hero.title':'మీ ఆరోగ్యం మా ప్రాధాన్యత','home.hero.subtitle':'AI-ఆధారిత నిర్ధారణ, నిపుణ డాక్టర్లు మరియు తక్షణ వైద్య అంతర్దృష్టులతో ప్రపంచ స్థాయి ఆరోగ్య సేవను అనుభవించండి.',
  'diagnosis.title':'AI ఆరోగ్య సహాయకుడు','assessment.title':'AI ఆరోగ్య మూల్యాంకనం','assessment.step1':'వ్యక్తిగత సమాచారం','assessment.step2':'లక్షణాలు','assessment.step3':'వైద్య చరిత్ర','assessment.step4':'జీవనశైలి','assessment.step5':'సమీక్ష',
  'assessment.fullName':'పూర్తి పేరు','assessment.age':'వయస్సు','assessment.gender':'లింగం','assessment.weight':'బరువు (కిలో)','assessment.bloodGroup':'రక్త వర్గం','assessment.phone':'ఫోన్ నంబర్','assessment.allergies':'అలర్జీలు','assessment.symptoms':'లక్షణాలు ఎంచుకోండి','assessment.analyze':'AI విశ్లేషణ పొందండి','assessment.analyzing':'AI మీ డేటాను విశ్లేషిస్తోంది...',
  'chat.title':'AI సంప్రదింపు','results.title':'మీ ఆరోగ్య విశ్లేషణ',
  'hospitals.title':'సమీప ఆసుపత్రులు కనుగొనండి','report.title':'వైద్య నివేదిక విశ్లేషకుడు','recovery.title':'వ్యక్తిగత రికవరీ ప్లాన్',
}

TRANSLATIONS.kn = { ...TRANSLATIONS.en,
  'nav.home':'ಮನೆ','nav.services':'ಸೇವೆಗಳು','nav.doctors':'ವೈದ್ಯರು','nav.appointments':'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು','nav.about':'ನಮ್ಮ ಬಗ್ಗೆ','nav.contact':'ಸಂಪರ್ಕಿಸಿ','nav.diagnosis':'AI ಆರೋಗ್ಯ',
  'common.next':'ಮುಂದೆ','common.previous':'ಹಿಂದೆ','common.submit':'ಸಲ್ಲಿಸಿ','common.cancel':'ರದ್ದು','common.back':'ಹಿಂದೆ','common.download':'ವರದಿ ಡೌನ್‌ಲೋಡ್','common.print':'ಮುದ್ರಿಸಿ','common.loading':'ಲೋಡ್ ಆಗುತ್ತಿದೆ...','common.yes':'ಹೌದು','common.no':'ಇಲ್ಲ','common.male':'ಪುರುಷ','common.female':'ಮಹಿಳೆ','common.other':'ಇತರ','common.required':'ಈ ಕ್ಷೇತ್ರ ಅಗತ್ಯ','common.getStarted':'ಪ್ರಾರಂಭಿಸಿ','common.learnMore':'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ','common.bookAppointment':'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ','common.beginAssessment':'ಮೌಲ್ಯಮಾಪನ ಪ್ರಾರಂಭಿಸಿ','common.aiHealthCheck':'AI ಆರೋಗ್ಯ ತಪಾಸಣೆ',
  'home.hero.title':'ನಿಮ್ಮ ಆರೋಗ್ಯ ನಮ್ಮ ಆದ್ಯತೆ','home.hero.subtitle':'AI-ಚಾಲಿತ ರೋಗ ನಿರ್ಣಯ, ತಜ್ಞ ವೈದ್ಯರು ಮತ್ತು ತಕ್ಷಣದ ವೈದ್ಯಕೀಯ ಒಳನೋಟಗಳೊಂದಿಗೆ ವಿಶ್ವ ದರ್ಜೆಯ ಆರೋಗ್ಯ ಸೇವೆ ಅನುಭವಿಸಿ.',
  'diagnosis.title':'AI ಆರೋಗ್ಯ ಸಹಾಯಕ','assessment.title':'AI ಆರೋಗ್ಯ ಮೌಲ್ಯಮಾಪನ','assessment.step1':'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ','assessment.step2':'ರೋಗಲಕ್ಷಣಗಳು','assessment.step3':'ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ','assessment.step4':'ಜೀವನಶೈಲಿ','assessment.step5':'ಪರಿಶೀಲನೆ',
  'assessment.fullName':'ಪೂರ್ಣ ಹೆಸರು','assessment.age':'ವಯಸ್ಸು','assessment.gender':'ಲಿಂಗ','assessment.weight':'ತೂಕ (ಕೆಜಿ)','assessment.bloodGroup':'ರಕ್ತ ಗುಂಪು','assessment.phone':'ಫೋನ್ ಸಂಖ್ಯೆ','assessment.allergies':'ಅಲರ್ಜಿಗಳು','assessment.symptoms':'ರೋಗಲಕ್ಷಣಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ','assessment.analyze':'AI ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಿರಿ','assessment.analyzing':'AI ನಿಮ್ಮ ಡೇಟಾವನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
  'chat.title':'AI ಸಮಾಲೋಚನೆ','results.title':'ನಿಮ್ಮ ಆರೋಗ್ಯ ವಿಶ್ಲೇಷಣೆ',
  'hospitals.title':'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಿ','report.title':'ವೈದ್ಯಕೀಯ ವರದಿ ವಿಶ್ಲೇಷಕ','recovery.title':'ವೈಯಕ್ತಿಕ ಚೇತರಿಕೆ ಯೋಜನೆ',
}

export function translate(key: string, language: LanguageCode): string {
  return TRANSLATIONS[language]?.[key] || TRANSLATIONS['en'][key] || key
}
export function getSpeechSynthesis() {
  if (typeof window !== 'undefined' && 'speechSynthesis' in window) return window.speechSynthesis
  return null
}
export function speak(text: string, language: LanguageCode) {
  const synthesis = getSpeechSynthesis()
  if (!synthesis) return
  const utterance = new SpeechSynthesisUtterance(text)
  utterance.lang = LANGUAGES[language].code
  utterance.rate = 0.9; utterance.pitch = 1; utterance.volume = 1
  synthesis.cancel(); synthesis.speak(utterance)
}
export function stopSpeaking() { getSpeechSynthesis()?.cancel() }
export function startListening(callback: (transcript: string) => void, language: LanguageCode) {
  if (typeof window === 'undefined') return null
  const SR = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition
  if (!SR) return null
  const recognition = new SR()
  recognition.lang = LANGUAGES[language].code
  recognition.continuous = false; recognition.interimResults = false
  recognition.onresult = (event: any) => {
    let transcript = ''
    for (let i = event.resultIndex; i < event.results.length; i++) transcript += event.results[i][0].transcript
    callback(transcript)
  }
  recognition.onerror = (event: any) => console.error('Speech error:', event.error)
  recognition.start(); return recognition
}
